name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the main branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - '1.6'
          - '1.9'
          - '~1.10.0-0'
          - 'nightly'
        julia-arch:
          - x64
        os:
          - ubuntu-latest
        include:
          # Add a few macOS jobs (not too many, the number we can run in parallel is limited)
          - julia-version: '1.6'
            julia-arch: x64
            os: macOS-latest
          - julia-version: 'nightly'
            julia-arch: x64
            os: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # For Codecov, we must also fetch the parent of the HEAD commit to
          # be able to properly deal with PRs / merges
          fetch-depth: 2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@latest
      - name: "Run tests"
        uses: julia-actions/julia-runtest@latest
      - name: "Run doctests"
        if: ${{ matrix.julia-version == '1.6' }}
        run: |
          julia --project=docs --color=yes --code-coverage -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            using Documenter: doctest
            using AlgebraicSolving
            doctest(AlgebraicSolving)'
      - name: "Process code coverage"
        uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src
      - name: "Upload coverage data to Codecov"
        continue-on-error: true
        uses: codecov/codecov-action@v2
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
